version: "3"
services:
  web:
    container_name: web
    hostname: web
    restart: always
    build: ./frontend/
    ports:
      - 8080:3000
    volumes:
      - ./news/images:/usr/src/app/public/img/news
    environment:
      - NODE_ENV=production
      - NEWS_URL=http://localhost:2368/
    links:
      - ghost

  ghost:
    container_name: ghost
    hostname: ghost
    image: ghost:2.2.2-alpine
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./news:/var/lib/ghost/content
    environment:
      - NODE_ENV=production
      - url=http://localhost:2368/
