version: "3"
services:
  web:
    restart: always
    build: ./express-docker/
    ports:
      - 8080:3000
    environment:
      - NODE_ENV=production
      
  ghost:
    image: ghost:2.2.2-alpine
    restart: always
    ports:
      - 8081:2368
    volumes:
      - "./ghost-docker:/var/lib/ghost/content"
    environment:
      - NODE_ENV=production
      - url=http://manage.mureedsultan.com/