version: "3"
services:
  web:
    container_name: web
    hostname: web
    restart: always
    build: ./express-docker/
    ports:
      - 8080:3000
    volumes:
      - ./ghost-docker/images:/usr/src/app/public/img/news
    environment:
      - NODE_ENV=production
    links:
      - ghost
      
  ghost:
    container_name: ghost
    hostname: ghost
    image: ghost:2.2.2-alpine
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./ghost-docker:/var/lib/ghost/content
    env_file:
     - ./ghost.env

  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./proxy/nginx:/etc/nginx/conf.d
      - ./proxy/certbot/conf:/etc/letsencrypt
      - ./proxy/certbot/www:/var/www/certbot
    links:
      - web

  certbot:
    container_name: certbot
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./proxy/certbot/conf:/etc/letsencrypt
      - ./proxy/certbot/www:/var/www/certbot