version: "3"
services:
  web:
    restart: always
    build: ./express-docker/
    ports:
      - 8080:3000
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=atgc.mureedsultan.com,www.atgc.mureedsultan.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=atgc.mureedsultan.com,www.atgc.mureedsultan.com
      - LETSENCRYPT_EMAIL=sultan.0313@gmail.com

  ghost:
    image: ghost:2.2.2-alpine
    restart: always
    ports:
      - 8081:2368
    volumes:
      - "./ghost-docker:/var/lib/ghost/content"
    environment:
      - NODE_ENV=production
      - url=http://manage.mureedsultan.com/
      - VIRTUAL_HOST=manage.mureedsultan.com,www.manage.mureedsultan.com
      - VIRTUAL_PORT=8081
      - LETSENCRYPT_HOST=manage.mureedsultan.com,www.manage.mureedsultan.com
      - LETSENCRYPT_EMAIL=sultan.0313@gmail.com
  
  # =========================================================================
  
  nginx-web:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx-web

networks:
  default:
    external:
      name: nginx-proxy