apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 6
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gitlab.mureedsultan.com:4567/sultan/atgc/frontend:latest
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: production
            - name: NEWS_URL
              value: https://news.advancedtelegeneticcounseling.com
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: atgc
